apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mw0ddeu9d-python 
  janus-idp.io/tekton: mw0ddeu9d-python
  backstage.io/kubernetes-id: mw0ddeu9d-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mw0ddeu9d-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  