apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mw0ddeu9d-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mw0ddeu9d-python 
  name: mw0ddeu9d-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mw0ddeu9d-python 
