apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mw0ddeu9d-python-gitops
  description: This is GitOps manifest for mw0ddeu9d-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: mw0ddeu9d-python
    backstage.io/kubernetes-id: mw0ddeu9d-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: mw0ddeu9d-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mw0ddeu9d-python
